### ISSUE TITLE
Latest daal4py doesn't work well under Ubuntu python 3 env.

### ISSUE THREAD

**Issue by jonasyang** [IntelPython/daal4py#109]
Repo:
1. Install latest anaconda.
2. Create clean env using: conda create -n test python=3.6.6.
3. Activate env:  conda activate test
4. Install daal4py: conda install -c intel daal4py.

Then just run python and use "import daal4py", I got the following error.
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import daal4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonas/anaconda3/envs/test/lib/python3.6/site-packages/daal4py/__init__.py", line 2, in <module>
    from _daal4py import *
  File "__init__.pxd", line 918, in init _daal4py
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
>>>

There is no error on windows with the same instructions. And if I use python=2.* on Linux, there is no errors too.

**Comment by oleksandr-pavlyk** [comment]
SAT-2477

**Comment by aguzmanballen** [comment]
@oleksandr-pavlyk this is quite old. Shall we close this ticket since the latest daal4py works fine?
