### ISSUE TITLE
Broken References in K-Means Initialization Parameter Documentation

### ISSUE THREAD

**Issue by racheloberman-intel** [IntelPython/daal4py#116]
Three of the K-Means Initialization parameters (nTrials, oversamplingFactor, & nRounds) say to refer to a section in references [1] or [2] . 

See image:
![brokenref](https://user-images.githubusercontent.com/52178578/60198114-bae71980-97f5-11e9-8993-bbd3c5bbdc91.PNG)

However, these references do not exist anywhere in the daal4py documentation or the Intel DAAL Dev documentation. I am unable to locate or edit these parameter descriptions in algorithms.rst, as they are automatically populated as members of an autoclass from  daal4py.kmeans_init.

See image:
![autoclass](https://user-images.githubusercontent.com/52178578/60198157-d4886100-97f5-11e9-9001-1eac71739cab.PNG)

Please add in the references and their corresponding sections to the daal4py documentation or remove the broken references.

**Comment by fschlimb** [comment]
@Alexander-Makaryev You can easily solve this by trimming comments which include "See section....".

**Comment by outoftardis** [comment]
@Alexander-Makaryev @fschlimb  I've removed "See section..." from comments in DAAL source code, so if you re-generate the docs, the issue should disappear. Please let me know if there are any problems still.

**Comment by outoftardis** [comment]
close this issues as it is not reproduced in a new [update](https://intelpython.github.io/daal4py/algorithms.html#k-means-initialization)

**Comment by Alexander-Makaryev** [comment]
Thanks a lot for your contribution
