### ISSUE TITLE
Expose daal::services::getNumberOfThreads in daal4py

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/daal4py#14]
Currently one can effectively call ``daal::services::setNumberOfThreads(n)`` via ``daal4py.daalinit(nthreads=n)``. 

In pyDAAL it used to be possible using ``nThreadsNew = Environment.getInstance().getNumberOfThreads()`` as seen in [this example](https://software.intel.com/en-us/daal-programming-guide-set-number-of-threads-py?language=en).

**Comment by fschlimb** [comment]
done with 082057e30ba96ac1ff72a99b6838a411a958ea1e
