### ISSUE TITLE
Replace default device by host device

### ISSUE THREAD

**Issue by Alexander-Makaryev** [IntelPython/daal4py#171]
In https://github.com/IntelPython/daal4py/blob/master/src/oneapi/oneapi.h when we have an issue with selecting of device the default device is selecting. It should be not the default but the host device because devices can have various priorities and the default device can be not the best choice.

**Comment by Alexander-Makaryev** [comment]
The issue is not resolved in your PR. It is already merged, so I provide the link to master branch
https://github.com/IntelPython/daal4py/blob/master/src/oneapi/oneapi.h#L52

**Comment by napetrov** [comment]
Per my understanding of problem in description the it is about scenario then we requested GPU device but it wasn't available so we failing back to default device.  - this was indeed fixes as now in case of problems in runtime we will not catch exception and it will be propagated.  
So with current behavior if we requested gpu device and it wasn't available we will fail.

on line that you've mention we use default device selection if not recognized device was pushed to sycl_context.  It not a runtime problem but usage model issue.   But i think we also can remove this to make less confusion for users if incorrect device will be passed to sycl_context

**Comment by Alexander-Makaryev** [comment]
There is no mention of the GPU in the issue.
Issue says that we should replace the default device selector with the host device selector.
In the current code it should be done when unknown device was specified.
At this moment FPGA has bigger priority then CPU so if environment contains FPGA or its emulation or driver or etc. and runtime decides that it can be chosen then we will fail because we don't support computations on FPGA.

**Comment by PetrovKP** [comment]
@Alexander-Makaryev 
Let's look at the following cases:
1. We choose `gpu` context and we have gpu - DPC++ will be use `gpu_selector`. **It Ok**.
2. We choose `gpu` context and we don't have gpu - DPC++ throw exception. User must handle this behavior himself. There will be no unexpected behavior. **It Ok**.
3. We choose `cpu` context and we have cpu - DPC++ will be use `cpu_selector`. **It Ok**.
4. We choose `cpu` context and we don't have cpu - DPC++ throw exception. User must handle this behavior himself. There will be no unexpected behavior. **It Ok**.
5. We choose other context - DPC++ will be use `default_selector`. At the same time, we warn him and I consider this to be normal behavior. Do you propose to throw an exception in this case?

**Comment by Alexander-Makaryev** [comment]
Default is FPGA. (see above comments when it is so)
We don't work with FPGA.
We should use host device instead if we want to fall back to some device and continue computation.
Or throw an error and don't go to host device. It is possible too.

We choose ``abc`` context and will be use ``default_selector``. In cases described above ( if environment contains FPGA or its emulation or driver or etc. and runtime decides that it can be chosen) it will be FPGA. We will fail with unclear error.
