### ISSUE TITLE
Ubuntu 18.04: ModuleNotFoundError: No module named 'daal4py'

### ISSUE THREAD

**Issue by abhi-84** [IntelPython/daal4py#188]
Hi
When I try to run any sample example using Anaconda & jupyter notebook in Ubuntu 18.04, it says
ModuleNotFoundError: No module named 'daal4py'

But I can run the same code on python interpretor and Ubuntu 16.04 via anaconda & Jupyter notebook.
Have anyone else identified this issue? I am experienceing this issue after I migrated to Ubuntu 18.04 itself. Any solution?
Thank you

**Comment by fschlimb** [comment]
@abhi-84 In the failing setup, does `conda list` list daal4py?

**Comment by abhi-84** [comment]
Yes.It shows daal4py in the list

**Comment by fschlimb** [comment]
Hm, could you please provide
1. The conda command you used to build your environment
2. The output of `conda list --explicit`
?

**Comment by abhi-84** [comment]
I jused following Conda command to build environmenmt:
conda create -n idp2 -c intel daal4py
conda activate idp2
conda install -c intel pandas
conda install -c intel jupyter notebook

Output of conda list --explicit

(idp2) abhi@ubuntu:~/Desktop/Intel-HPC$ conda list --explicit
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/intel/linux-64/icc_rt-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/intel/linux-64/impi_rt-2019.6-intel_166.tar.bz2
https://conda.anaconda.org/intel/linux-64/intel-openmp-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/intel/linux-64/intelpython-2020.0-1.tar.bz2
https://conda.anaconda.org/intel/linux-64/libgcc-ng-9.1.0-hdf63c60_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/openssl-1.1.1d-0.tar.bz2
https://conda.anaconda.org/intel/linux-64/tbb-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/intel/linux-64/tcl-8.6.4-24.tar.bz2
https://conda.anaconda.org/intel/linux-64/bzip2-1.0.8-0.tar.bz2
https://conda.anaconda.org/intel/linux-64/daal-2020.0-intel_166.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.6-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.1.2-h6c8ec71_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-h9c2bf20_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://conda.anaconda.org/intel/linux-64/libffi-3.2.1-11.tar.bz2
https://conda.anaconda.org/intel/linux-64/libsodium-1.0.16-3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.13-h1bed415_1.conda
https://conda.anaconda.org/intel/linux-64/mkl-2020.0-intel_166.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.43-he6710b0_0.conda
https://conda.anaconda.org/intel/linux-64/sqlite-3.29.0-0.tar.bz2
https://conda.anaconda.org/intel/linux-64/tk-8.6.4-29.tar.bz2
https://conda.anaconda.org/intel/linux-64/xz-5.2.4-h14c3975_7.tar.bz2
https://conda.anaconda.org/intel/linux-64/zlib-1.2.11-h14c3975_7.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.63.1-h5a9c865_0.conda
https://conda.anaconda.org/intel/linux-64/libpng-1.6.36-2.tar.bz2
https://conda.anaconda.org/intel/linux-64/libxml2-2.9.9-h14c3975_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.2.3.2-0.conda
https://conda.anaconda.org/intel/linux-64/python-3.7.4-hf484d3e_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.1-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/certifi-2019.9.11-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.12-h746ee38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/entrypoints-0.3-py37_0.conda
https://conda.anaconda.org/intel/linux-64/freetype-2.10.1-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-hb453b48_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py37_0.conda
https://conda.anaconda.org/intel/linux-64/kiwisolver-1.0.1-py37_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-1.1.1-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mistune-0.8.4-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/more-itertools-8.0.2-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandocfilters-1.4.2-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.7.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py37_0.conda
https://conda.anaconda.org/intel/linux-64/pyparsing-2.2.0-py37_2.tar.bz2
https://conda.anaconda.org/intel/linux-64/pytz-2019.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-18.1.0-py37he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/send2trash-1.5.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/simplegeneric-0.8.1-py37_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-4.19.8-py37hf484d3e_0.conda
https://conda.anaconda.org/intel/linux-64/six-1.12.0-py37_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/tbb4py-2020.0-py37_intel_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.4.4-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.0.3-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wcwidth-0.1.7-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py37_1.conda
https://conda.anaconda.org/intel/linux-64/cycler-0.10.0-py37_7.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.13.0-h9420a91_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-hbbd80ab_1.conda
https://conda.anaconda.org/intel/linux-64/mkl-service-2.3.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.7.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.15.6-py37h7b6447c_0.conda
https://conda.anaconda.org/intel/linux-64/python-dateutil-2.8.0-py37_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/setuptools-41.0.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/terminado-0.8.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-4.3.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/zipp-0.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bleach-3.1.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib_metadata-1.3.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.10.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-4.6.1-py37_0.conda
https://conda.anaconda.org/intel/linux-64/numpy-base-1.17.4-py37_4.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.5.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.9.7-h5867ecd_1.conda
https://conda.anaconda.org/intel/linux-64/wheel-0.31.0-py37_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-3.2.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-5.3.4-py37_0.conda
https://conda.anaconda.org/intel/linux-64/mkl_fft-1.0.15-py37ha68da19_3.tar.bz2
https://conda.anaconda.org/intel/linux-64/mkl_random-1.1.0-py37ha68da19_0.tar.bz2
https://conda.anaconda.org/intel/linux-64/pip-19.1.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/prompt_toolkit-1.0.15-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.9.2-py37h05f1152_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-5.8.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nbformat-4.4.0-py37_0.conda
https://conda.anaconda.org/intel/linux-64/numpy-1.17.4-py37ha68da19_4.tar.bz2
https://conda.anaconda.org/intel/linux-64/daal4py-2020.0-py37ha68da19_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-5.1.3-py37h39e3cac_0.conda
https://conda.anaconda.org/intel/linux-64/matplotlib-3.1.1-py37_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/nbconvert-5.6.1-py37_0.conda
https://conda.anaconda.org/intel/linux-64/numexpr-2.7.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_console-5.2.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/notebook-6.0.2-py37_0.conda
https://conda.anaconda.org/intel/linux-64/pandas-0.25.1-py37_3.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/qtconsole-4.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/widgetsnbextension-3.5.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipywidgets-7.5.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter-1.0.0-py37_7.conda

**Comment by fschlimb** [comment]
With your set of packages I can import daal4py and print the version.

Does `python -c "import daal4py; print(daal4py.__version__)"` work for you (in the above conda env)?

**Comment by abhi-84** [comment]
As I have told, with python interpretor, it works perfectly.probowm happens
when I try to import daal4py in jupyter notebook. Then it says module not
found.

**Comment by fschlimb** [comment]
I suspect this is a environment/jupyter setup issue, not an issue in daal4py itself.

Technically I would advice to inspect linker debug output (like setting 'LD_DEBUG=files') to see if there is a dependence that is not met on your system.

Please also visit Intel Community forum for help at https://forums.intel.com/

**Comment by abhi-84** [comment]
I understand that this might be a issue with environment or jupyter but
does it works with jupyter at your end?
Or is it system specific error?

**Comment by fschlimb** [comment]
I installed the exact same conda env on an Ubuntu 18.04 system, started an empty jupyter notebook and succesfully imported daal4py as well as printed the version.

**Comment by abhi-84** [comment]
Ok.
I will try that.Thanks for helping me

**Comment by abhi-84** [comment]
Have u used the same method to create environment and install daal4py or is
their any other special method?

**Comment by fschlimb** [comment]
I copied your package list into file '188.txt' and used "conda create --name 188 --file 188.txt"

**Comment by abhi-84** [comment]
Will this command would help me to create environment and install daal4py?

**Comment by fschlimb** [comment]
It will create a new conda env with the name 188 which is a duplicate of yours.
'conda activate 188' will activate it.

**Comment by abhi-84** [comment]
I reinstalled my Ubuntu and It works perfectly.
Thanks
