### ISSUE TITLE
DAAL SVM performance vs sklearn 0.22

### ISSUE THREAD

**Issue by mayujsw** [IntelPython/daal4py#197]
I tried SVM with webpage_train.csv (This dataset has 23187 samples with 300 features, 2 classes) with scikit-learn and DAAL4PY on intel cascade lake server. It turns out scikit-learn can finish the training quickly, but i've run with daal4py for like several minutes (to run the origianl scikit-learn script with -m daal4py), it did not finished. And libdaal_core.so keeps as hottest spot through perf top. 

I'd like to confirm that is it as expected. that daal svm lags behind sklearn on svm ? or I need to check/tweak anything to make daal perform better.

**Comment by mayujsw** [comment]
hi any update there ?

**Comment by Alexander-Makaryev** [comment]
@PetrovKP @SmirnovEgorRu Could you please provide some comments?

**Comment by PetrovKP** [comment]
@mayujsw You can set the cash size parameter is `n_samples` x `n_samples` x `sizeof(TYPE)` - A case of you:
```python
    svm_train = daal4py.svm_training(
        cacheSize=int(8 * 23187 * 23187),
        ...
    )
```
If you provide more information - with what parameters and so on did you run, we will try to fix it or suggest something else for resolve this problem.

**Comment by mayujsw** [comment]
@PetrovKP , thank you for this suggestion.

the quesiton is i run daaly through monkey patch on scikit scipt, the parameter of scikit svm cachesize is MB, if I set the cachesize to the formula as you commented, will it do unit conversion

**Comment by mayujsw** [comment]
BTW, the monkey patch mode does not work on scikit-0.23-dev0. is that a known issue , Thanks

**Comment by PetrovKP** [comment]
@mayujsw 

> the quesiton is i run daaly through monkey patch on scikit scipt, the parameter of scikit svm cachesize is MB, if I set the cachesize to the formula as you commented, will it do unit conversion

If you work with monkey patch on scikit then enough in MB `int(8 * 23187 * 23187 // 1024 // 1024)` ~ `4040 MB`'

In the near future, we plan to improve the caching strategy, but so far the biggest performance will be achieved only in this case.

**Comment by PetrovKP** [comment]
We added ThunderSVM method for SVM in DAAL2020.2 (available in [conda](https://anaconda.org/intel/daal)) . It works significant faster than the current version SMO and doesn't have strong dependency on cache size - works with any size optimally.

Use:
```python
    svm_train = daal4py.svm_training(
        method='thunder',
        cacheSize=8000000,
        ...
    )
```
