### ISSUE TITLE
Sklearn integration of RF predict uses float fptype always for daal4py

### ISSUE THREAD

**Issue by SmirnovEgorRu** [IntelPython/daal4py#206]
https://github.com/IntelPython/daal4py/blob/ca67cc2d070ff27318e210e4b74f05ab7b9fa1d0/daal4py/sklearn/ensemble/decision_forest.py#L285

Looking at the code - we use float type always for RF predict. Probably, it's handled in another place, but it looks like an issue.

**Comment by PivovarA** [comment]
Done
