### ISSUE TITLE
undefined symbol: _ZNK2cl4sycl7program10get_kernelESs

### ISSUE THREAD

**Issue by zjin-lcf** [IntelPython/daal4py#257]
Could you reproduce the following issue after the installation of oneAPI ?  Thanks

~/daal4py/examples/sycl$ python covariance_batch.py
Traceback (most recent call last):
  File "covariance_batch.py", line 24, in <module>
    from daal4py.oneapi import sycl_buffer
  File "/opt/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/daal4py/oneapi/__init__.py", line 1, in <module>
    from _oneapi import sycl_context, sycl_buffer, is_in_sycl_ctxt
ImportError: /opt/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/_oneapi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2cl4sycl7program10get_kernelESs

**Comment by michael-smirnov** [comment]
Hi @zjin-lcf 
Yes, we can, thanks for raising this!
While we are fixing it, I can suggest you re-build daal4py package as a workaround:
1. Setup environment of oneAPI package 
```sh
source /opt/intel/oneapi/setvars.sh
```
2. Checkout & update `master` branch of your local daal4py repo from github
3. Set additional env variables required for daal4py building:
```sh
export DPCPPROOT=/opt/intel/oneapi/compiler/latest
export DAALROOT=/opt/intel/oneapi/daal/latest
export TBBROOT=/opt/intel/oneapi/tbb/latest
``` 
4. Create & activate conda environment:
```sh
conda create -q -y -n CB python=3.7 conda-build conda-verify
conda activate CB
```
5. Start building from the root of daal4py repo folder:
```sh
conda build --override-channels -c conda-forge -c intel conda-recipe
```

After that, you will be able to use the package built inside CB conda environment.

**Comment by zjin-lcf** [comment]
Can you please list the entire steps ?  After step 5, is there an installation step using 'conda install' ?  The steps listed are not the same as the steps listed below.  

```
Installing the built daal4py conda package
conda install <path-to-conda-package-as-built-above>
To actually use your daal4py, dependent packages need to be installed. To ensure, do

Linux and OsX:

conda install -c intel -c conda-forge mpich daal numpy
```
This may cause confusion.

**Comment by napetrov** [comment]
@zjin-lcf  sorry for missing your last question
for this you need to install daal4py package created as result of conda build command. 
And not for installing remaining packages is just to cover required dependencies for daal4py

Also would like to add: 
1. Problem with undefined symbol is fixed in latest oneAPI releases
2. README.md updated with instruction for DPC++ build
