### ISSUE TITLE
Issue & Pr-Templates.MD Files

### ISSUE THREAD

**Issue by ritiksoni00** [IntelPython/daal4py#314]
It is Need for Easy communication! 
I

**Comment by napetrov** [comment]
For this fix - templates can be taken from https://github.com/oneapi-src/oneDAL/tree/master/.github repo

**Comment by ritiksoni00** [comment]
Thank you @napetrov :))

**Comment by napetrov** [comment]
@ritiksoni00  - PR templates are working now.
But not issues templates.  could you please take a look why they don't work?

**Comment by napetrov** [comment]
Even with last one - issue templates are not applied

**Comment by ritiksoni00** [comment]
i saw somewhere i think :- 
go to  setting of repo
then in the Feature section, we have to add issues templates by checking the box like this
![Screenshot 2020-10-05 143158](https://user-images.githubusercontent.com/47344024/95060192-91ff4500-0717-11eb-8b95-fb6d7a548917.jpg)

**Comment by napetrov** [comment]
I've add it via interface

**Comment by ritiksoni00** [comment]
idk why my template didn't work?

**Comment by napetrov** [comment]
i guess path - as you can see in repo now - they are different.
