### ISSUE TITLE
Add Windows CI build with oneAPI support on Azure DevOps CI

### ISSUE THREAD

**Issue by napetrov** [IntelPython/daal4py#317]
Please enable Windows CI build with oneAPI support similar to current CI done for linux 

You can find examples of Azure CI setup here: 
https://github.com/oneapi-src/oneapi-ci

For build you would need oneDAL and DPC++ compiler from toolkit, and they have to be selected only - as entire toolkit is quite large.

For CI env scripts setup - please use .ci/  directory using this as structure example - https://github.com/oneapi-src/oneDAL/tree/master/.ci. Pipeline file can be keept as is for now in it's current place. 

Components names in installer: 

C:\w_basekit_extracted>bootstrapper.exe --list-components

==================================================================================================================
intel.oneapi.win.vtune           2021.1-575.beta08          Intel┬« VTune(TM) Profiler
intel.oneapi.win.tbb.devel       2021.1-561.beta08          Intel┬« oneAPI Threading Building Blocks
intel.oneapi.win.dpcpp-library   2021.1-864.beta08          Intel┬« oneAPI DPC++ Library
**intel.oneapi.win.dpcpp-compiler  2021.1-864.beta08          Intel┬« oneAPI DPC++ Compiler**
intel.oneapi.win.dnnl            2021.1-474.beta08          Intel┬« oneAPI Deep Neural Network Library
**intel.oneapi.win.daal.devel      2021.1-536.beta08          Intel┬« oneAPI Data Analytics Library**
intel.oneapi.win.dpcpp_ct.common 2021.1-519.beta08          Intel┬« DPC++ Compatibility Tool
intel.oneapi.win.mkl.devel       2021.1-487.beta08          Intel┬« oneAPI Math Kernel Library
intel.oneapi.win.vpl             2021.1-464.beta08          Intel┬« oneAPI Video Processing Library
intel.oneapi.win.python3         2021.1-514.beta08          Intel┬« Distribution for Python*
intel.oneapi.win.advisor         2021.1-519.beta08          Intel┬« Advisor
intel.oneapi.win.dpcpp_debugger  10.0-62.beta08             GDB*
intel.oneapi.win.ipp.devel       2021.1-504.beta07          Intel┬« Integrated Performance Primitives
intel.oneapi.win.ippcp           2021.1-68.beta07           Intel┬« Integrated Performance Primitives Cryptography

**Comment by PetrovKP** [comment]
@napetrov We have done this task. Can we close it?
