### ISSUE TITLE
Add computation of leftSingularMatrix to distributed SVD

### ISSUE THREAD

**Issue by fschlimb** [IntelPython/daal4py#50]
- add an extra step (Distributed<step3>) to corresponding entry in ```wrappers.py:has_dist```
- Most work will be adding the new pattern
  - use something like ```map-reduce-star-plus``` if same can be used for QR(#49)
  - otherwise follow ```dist_custom``` pattern
- add using leftSingularMatrix to svd examples

**Comment by Alexander-Makaryev** [comment]
implemented
