### ISSUE TITLE
Intel oneDAL FATAL ERROR on Windows10

### ISSUE THREAD

**Issue by CHDev93** [IntelPython/daal4py#514]
**Describe the bug**
The windows wheel is unable to load the dll's needed to run the examples. I tried one of the examples and got the following when calling a library function

Intel oneDAL FATAL ERROR: onedal_thread.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: onedal_sequential.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.
Intel oneDAL FATAL ERROR: onedal_thread.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: onedal_sequential.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.

**To Reproduce**
1. `pip install daal4py pandas lightgbm` on Windows10
2. Alter the `__init__.py` to have `path_to_libs = os.path.join(os.path.dirname(sys.executable), "..\\Library\\bin")` (note the `..`)
3. Run the following script
```python
import lightgbm as lgb
import numpy as np
import daal4py as d4p


def get_data(n, m):
    x_train = np.random.randn(n, m).astype(np.float32)
    A = np.random.randint(-5, 5, size=(m, 1))
    y_train = (x_train @ A).astype(np.float32)

    return x_train, y_train

n = 1000
m = 25
x_train, y_train = get_data(n, m)

params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': ['rmse'],
    'device': 'cpu',
    'num_leaves': 31,
    'bagging_fraction': 0.5,
    'feature_fraction': 0.5,
    'learning_rate': 0.001,
    'verbose': 2,
    'max_bin': 255,
}
ds_train = lgb.Dataset(x_train, y_train.ravel())#, free_raw_data=False)
gbm = lgb.train(
    params,
    ds_train,
    num_boost_round=10,
    # keep_training_booster=args.keep_training_booster,
)

print("Converting...", flush=True)
daal_model = d4p.get_gbt_model_from_lightgbm(gbm)
print("Converted...", flush=True)
daal_prediction = d4p.gbt_regression_prediction().compute(x_train, daal_model).prediction
```

3. See output
```
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.000021 seconds, init for row-wise cost 0.000844 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001624 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6375
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 25
[LightGBM] [Info] Start training from score 0.386410
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 6
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
Converting...
Converted...
Intel oneDAL FATAL ERROR: onedal_thread.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: onedal_sequential.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.
Intel oneDAL FATAL ERROR: onedal_thread.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: onedal_sequential.1.dll. Error code is 0x80096005.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.
```

**Expected behavior**
Successfully converted lightgbm model

**Output/Screenshots**
Would note that I do see the dlls in the correct folder and the directory is added to PATH

**Environment:**
 - OS: Windows10
 - Compiler: ?
 - Version: ?
 - Python: 3.6.6

**Comment by PetrovKP** [comment]
@CHDev93 Thank you for Issue. How was python installed - conda / venv / default python?

> Alter the __init__.py to have path_to_libs = os.path.join(os.path.dirname(sys.executable), "..\\Library\\bin") (note the ..)

Change in `__init__.py` solved the problem for you?

**Comment by CHDev93** [comment]
Thanks for the quick follow up @PetrovKP. I'm working in a python virtualenv (some differences with venv but don't know the ins and outs). 

The change in the init.py gets around a different bug where the package fails on import. I think this should be fixed upstream but I'm a bit confused because the changes in [this PR](https://github.com/IntelPython/daal4py/pull/488/files) haven't been merged yet but that's exactly what I have in my init.py just from `pip install daal4py`. 

After fixing the init.py, the package imports ok but I get an error at `daal_prediction = d4p.gbt_regression_prediction().compute(x_train, daal_model).prediction`

I also ran one of the sample classification decision tree examples and got the same DLL load error so I think it's a generic install issue rather than specific to my script

**Comment by PetrovKP** [comment]
@CHDev93 Thanks you!

 I was able to reproduce your first problem.  The problem lies in the virtual environment, where the paths to python are different. We will definitely fix this in the near future.

As a temporary solution to check the functionality, I modified `__init__.py`:

```python
if "Windows" in platform.system():
    import os
    import sys
    path_to_libs_2 = os.path.join(os.path.dirname(sys.executable), "..\\",  "Library\\bin")
    print(path_to_libs_2)
    if sys.version_info.minor >= 8:
        os.add_dll_directory(path_to_libs_2)
    os.environ['PATH'] += os.pathsep + path_to_libs_2
```

And you script worked successfully:

<details><summary>[Click to expand] </summary>

```
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.000233 seconds, init for row-wise cost 0.001710 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005067 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6375
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 25
[LightGBM] [Info] Start training from score -0.435602
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
Converting...
Converted...
```
 </details>

But have you done this and see another problem? Right? Can you share your versions of oneDAL? in general, the path to dll of oneDAL should solve all problems. very strange...

P.S. My flow:
```bash
python -m pip install --user virtualenv
python -m venv env
.\env\Scripts\activate
pip install daal4py lightgbm
python <your_script.py>
```
where python 3.6.7 and windows 10

**Comment by CHDev93** [comment]
virtualenv issue makes sense, thanks for confirming! Regarding the version of oneDAL, do you just mean my version version of daal4py? The following is the result of `pip freeze -l`
```
common-cmplr-lib-rt==2021.1.2
common-cmplr-lic-rt==2021.1.2
daal==2021.1.2
daal4py==2021.1
dpcpp-cpp-rt==2021.1.2
intel-openmp==2021.1.2
joblib==1.0.1
lightgbm==3.1.1
numpy==1.19.5
opencl-rt==2021.1.2
pandas==1.1.5
python-dateutil==2.8.1
pytz==2021.1
scikit-learn==0.24.1
scipy==1.5.4
six==1.15.0
tbb==2021.1.1
threadpoolctl==2.1.0
```

I very clearly see all the dlls that are not being found inside `my_env/Library/bin` so I'm not sure why it's not being picked up (created a fresh virtualenv just in case). I tried preprending `path_to_libs` to PATH rather than appending and didn't have any success with that

**Comment by PetrovKP** [comment]
@CHDev93  This is not a problem with finding a library. Otherwise there would be errors:
```
Intel oneDAL FATAL ERROR: Cannot find/load library onedal_thread.1.dll.
Intel oneDAL FATAL ERROR: Cannot find/load library onedal_sequential.1.dll.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.
Intel oneDAL FATAL ERROR: Cannot find/load library onedal_thread.1.dll.
Intel oneDAL FATAL ERROR: Cannot find/load library onedal_sequential.1.dll.
Intel oneDAL FATAL ERROR: Cannot load neither onedal_thread.1.dll nor onedal_sequential.1.dll.
```

Your error is more exotic ([from the forum](https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_start-windows_10/error-0x80096005/b973f073-ec8f-475e-a543-9cc453d7bdbc)): 
```
0x80096005 -2146869243 TRUST_E_TIME_STAMP The timestamp signature and/or certificate could not be verified or is malformed.
```

For loader onedal_thread and onedal_sequential we use safe `WinVerifyTrust` checks, most likely there are some problems.

We will try to deal with the problem in detail. As the news, we will definitely unsubscribe

**Comment by CHDev93** [comment]
Really appreciate you looking into this @PetrovKP . The forum you linked to seems to indicate this is something specific to my Windows setup. My takeaway was that there wasn't anything the library could do about this but some sort of patching I need on my machine. Is that your understanding as well?

**Comment by PetrovKP** [comment]
@CHDev93 I also think so at the moment.

**Comment by PetrovKP** [comment]
@CHDev93 DLL of oneDAL cannot verify the certificate on your system. Can you check the certificate properties to see if this is the problem?
![image](https://user-images.githubusercontent.com/17429885/107682852-ef049c00-6cb1-11eb-9f71-fac9440197c8.png)

**Comment by chaaland** [comment]
@PetrovKP I have a very similar "Digital Signature Details" page except the signing time is "12 November 2020 10:43:51". Specifically there is no day of the week and the date is order day, month, year rather than month day year. When I click "View Certificate", the general tab shows "The timestamp signature and/or certificate could not be verified or is malformed". The date certainly looks valid to me unless it's really not happy about european date formatting.

So this is certainly the problem as you mention, though I'm not familiar enough with these things to know how to proceed.

**Comment by PetrovKP** [comment]
@chaaland Unfortunately, it's hard for me to reproduce.  Updating certificates at the root can potentially help:

1. Download https://www.digicert.com/util/ digicert certificate utility
2. Run the utility and from the menu select “tools” and then AutoRootUpdate.
3. Change the setting to ‘Disabled’ . (Yes ‘Disabled’).

[Reference](https://community.logmein.com/t5/GoToAssist-Remote-Support/GoTo-Opener-Error-quot-Timestamp-signature-or-certificate-could/m-p/254105#M6375)

**Comment by chaaland** [comment]
@PetrovKP thanks for digging this up! I will attempt this fix and report back soon

**Comment by CHDev93** [comment]
@PetrovKP managed to fixed this with your comments regarding the root certificate update. Thanks for your help!

Regarding the init.py not working for `virtualenv` on windows, should I create a separate issue?

**Comment by PetrovKP** [comment]
@CHDev93 Great news!

Today we have merged the [fix ](https://github.com/IntelPython/daal4py/pull/488)for the virtualenv issue.

**Comment by PetrovKP** [comment]
@CHDev93  Do you mind if I close the issue, but at the same time move this thread to the [discussion ](https://github.com/IntelPython/daal4py/discussions) so that the question and the solution can be seen by everyone?

**Comment by CHDev93** [comment]
Yes, happy to have this issue closed off and moved elsewhere if you think that's the most appropriate place for it to live
