### ISSUE TITLE
add windows CI

### ISSUE THREAD

**Issue by fschlimb** [IntelPython/daal4py#59]
ADD appveyor CI
@anton-malakhov might be able to help

**Comment by anton-malakhov** [comment]
I've done it for BlackScholes adding both Python environments and icc compilation, please refer to https://github.com/IntelPython/BlackScholes_bench/blob/master/appveyor.yml and corresponding scripts. I used bash as a cross-platform the scripting language everywhere.

**Comment by fschlimb** [comment]
I tried with Azure Pipelines, which looks pretty slick.

@Alexander-Makaryev For some reason it can't load the created dll. I guess we need to download the created package and debug locally.

https://dev.azure.com/frankschlimbach/daal4py/_build/results?buildId=19

@tomashek @oleksandr-pavlyk Once again, we see weird package resolution: despite --override-channels it picks numpy from default, where I'd like it to use intel. Any idea?
