### ISSUE TITLE
Native pandas dataframe handling

### ISSUE THREAD

**Issue by triskadecaepyon** [IntelPython/daal4py#6]
Most algorithms in daal4py take numpy arrays, but this is an extra step that most data scientists prefer not to have to do.

It would be easier to be able to put in a direct Dataframe instead of a NumPy array into the models, as we normally just call '.values' anyways.

It would go from this:
```
target = np.array(dataset.columnname.values, ndmin=2).T
d4p_lm = d4p.linear_regression_training(interceptFlag=True)
lm_trained = d4p_lm.compute(feature_dataset.values, target)
```

to this:
```
d4p_lm = d4p.linear_regression_training(interceptFlag=True)
lm_trained = d4p_lm.compute(feature_dataset, target_df_or_series)
```

Note that this would 1) simplify the calls if using a single Y vector to not have the above numpy array cast, and 2) would allow us to keep internal information (such as column names and dropped feature frames) within the model.  Both of these would be good additions to daal4py.

**Comment by fschlimb** [comment]
Down with 29f5c75c446466cb79bf774ee35b704b32c062ef
