### ISSUE TITLE
Add better print behavior for low_order_moments()

### ISSUE THREAD

**Issue by triskadecaepyon** [IntelPython/daal4py#7]
The low order moments class has the advantage of being able to process an entire array of features, but does not make it easy to see the results without individually selecting it.  

For printing the entire result array, it would be preferred to print ALL of the results if using the print() function.

```
metrics_processor = d4p.low_order_moments()
data = metrics_processor.compute(dataset.values)
print(data) # this does not do anything smart at the moment
print(data.standardDeviation) # but this does print the result array
```

From a data scientist perspective, better printing behavior would be useful especially in the Jupyter Notebook arena.  Consequently if you add Dataframe support, it might make it easier for easier printing.

**Comment by oleksandr-pavlyk** [comment]
It's a matter of implementing `__str__` method for the result.

The result may contain the following fields: `minimum`, `maximum`, `mean`, `standardDeviation`, `variance`, `variation`, `sum`, `sumSquared`, `sumSquaresCentered`, `secondOrderRawMoment`. 

I suppose the default 'smart' printing would display min, max, mean and std if available, kind of like `summary` function does in R.

It makes sense to arrange the data into a table. Perhaps reuse pandas for printing?

How about a code that maps `low_order_result` to a pandas's dataframe?

**Comment by fschlimb** [comment]
I would like to think about the broader picture. The same 'issue' exists for all results/models.

I suggest adding a __str__ method to all results and models
* printing attribute names and value for standard/trivial types (integer, str, float etc)
* printing attribute name and a summary for non-trivial, non-daal types
  * 'array' (or similar), dtype and shape for numpy arrays
  * 'dict' (or alike) and size
  * as far as I can tell there are no other non-trivial, non-daal types used
* printing attribute name and daal type for daal types (like models)

Attributes which are not expanded (complex and daal types) can be expanded by explicitly printing them.

A conversion to a pandas data-frame seems applicable only in very special cases, like low order moments. A conversion to a dict looks more generic. pandas allows creating DFs from dicts.

@Alexander-Makaryev

**Comment by fschlimb** [comment]
For algorithms we could print the parameters. This is more involved and probably less important.

**Comment by triskadecaepyon** [comment]
Yes, I'll second @fschlimb 's findings.  It is mostly about having __str__ methods when looking at a summary, and accessors to the values in the right type when needing a specific one (mean, variance as examples).

**Comment by fschlimb** [comment]
done: generic print capability added for results and model through #48
